apiVersion: v1
kind: Service
metadata:
  name: pcc-gateway
  labels:
    app: pcc-gateway
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: pcc-gateway
  sessionAffinity: None
